preferences:
  autowire-on-sync-mode: UPDATE_OPTIONAL_DEPENDENCIES
  repositories-mode: FAIL_ON_PROJECT_REPOS

repositories:
  gradle-plugin-portal:
    scope: PLUGINS
  google:
  maven-central:
  jit-pack:

plugins:
  com.android.application:
    alias: android-application
    version: 8.13.0
  com.android.library:
    alias: android-library
    version-ref: android-application
  org.jetbrains.kotlin.android:
    alias: kotlin-android
    version: 2.2.10
  com.vanniktech.maven.publish:
    alias: maven-publish
    version: 0.34.0

libraries:
  io.noties.markwon:
    core:
      version: 4.6.2
    image:
      version-ref: <this>::core
    html:
      version-ref: <this>::core
  com.squareup.okhttp3:
    okhttp:
      version: 5.1.0
  androidx.lifecycle:
    lifecycle-runtime-ktx:
      version: 2.9.3
  androidx.core:
    core-ktx:
      version: 1.17.0
  androidx.appcompat:
    appcompat:
      version: 1.7.1
  com.google.android.material:
    material:
      version: 1.13.0
  androidx.constraintlayout:
    constraintlayout:
      version: 2.2.1
  androidx.test.ext:
    junit:
      version: 1.3.0
  androidx.test.espresso:
    espresso-core:
      version: 3.7.0
  junit:
    junit:
      version: 4.13.2